CREATE TABLE IF NOT EXISTS /*TABLE_PREFIX*/t_advantages (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(255) NOT NULL,
	`description` TEXT NULL,
	`avatar` VARCHAR(255) NULL,
	`orderliness` TINYINT(2) UNSIGNED NULL,
	PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;